//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyService")]
public interface IMyService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Delay", ReplyAction="http://tempuri.org/IMyService/DelayResponse")]
    int Delay(int timespan);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/TestOut", ReplyAction="http://tempuri.org/IMyService/TestOutResponse")]
    int TestOut(out System.DateTime time);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/TestByRef", ReplyAction="http://tempuri.org/IMyService/TestByRefResponse")]
    void TestByRef(long foo, ref int test, out System.DateTime time);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMyServiceChannel : IMyService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MyServiceClient : System.ServiceModel.ClientBase<IMyService>, IMyService
{
    
    public MyServiceClient()
    {
    }
    
    public MyServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Delay(int timespan)
    {
        return base.Channel.Delay(timespan);
    }
    
    public int TestOut(out System.DateTime time)
    {
        return base.Channel.TestOut(out time);
    }
    
    public void TestByRef(long foo, ref int test, out System.DateTime time)
    {
        base.Channel.TestByRef(foo, ref test, out time);
    }
}
